version: '2'

services:
  web:
    image: registry.gitlab.com/tmwebdev/westpoint
    restart: always
    expose:
      - 80
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.basic.frontend.rule=Host:westpointrealtors.com"

networks:
  web:
    external:
      name: global_web
